---
- name: NODEJS | INSTALL NODEJS & YARN
  apt:
    name:
      - nodejs
      - npm
    update_cache: true
- name: "NODEJS | NPM INSTALL GLOBAL PACKAGE"
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ npm_globals }}"